name: Deploy static files to uniquemo.github.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      - name: push build files to uniquemo.github.io
        uses: uniquemo/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'dist/*'
          destination_repo: 'uniquemo/uniquemo.github.io'
          destination_folder: 'tools'
          user_email: 'myx3901051@qq.com'
          user_name: 'uniquemo'
          commit_message: 'doc: automatic message to update vue tools app'
